keys:
  - &admin_sincore age10rvdume3yfwjxu2wc64dmkmc06qsm7fe0fvrpqt8mdrdksqx75vspwns56
  - &workstation_sushi age10e6ptnwuy76r2rx7cncp5gvh06eghvdungnhrkkea8t32caxjdxshwcy83
  - &server_ramen age1gpm5lk2hvq49nxzr995ds9ps6u0vvkm2ve5rjxt4zv6sqj28symsq6cwmm
creation_rules:
  - path_regex: secrets/default.yaml$
    key_groups:
      - age:
          - *admin_sincore
          - *workstation_sushi
          - *server_ramen
  - path_regex: secrets/tailscale/default.yaml$
    key_groups:
      - age:
          - *admin_sincore
          - *workstation_sushi
          - *server_ramen
  - path_regex: secrets/networking/default.yaml$
    key_groups:
      - age:
          - *admin_sincore
          - *workstation_sushi
          - *server_ramen
  - path_regex: secrets/development/openai.yaml$
    key_groups:
      - age:
          - *admin_sincore
          - *workstation_sushi
