networking:
  wireless:
    home:
      ssid: ENC[AES256_GCM,data:e5lm2ggKOyef/Rtj8EbEHQ==,iv:4w8oQZr+Zlb/nEO5/k1qB05ZU7duMXxyq2VrL1+OQG8=,tag:yVxWUImWTg5UB/EKQzz3EQ==,type:str]
      password: ENC[AES256_GCM,data:6rBXbXqxt3g=,iv:jT7UBvFbce5YsqxDrgEbJQn7a8p1cInk2JXL1BiVwJ4=,tag:9OVpoCQObpv3ZTjc0tY1vQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10rvdume3yfwjxu2wc64dmkmc06qsm7fe0fvrpqt8mdrdksqx75vspwns56
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Qm04bHpCckFDcDY2Rnoy
        SGg5QzlncXVQaGRrN2pxTUNndTVoaFdkT1YwClhYb1hwNFFNSmRPemFSNHJ0aU1y
        QWN1bjVZU2phYndrSzkveFhDazBZVjAKLS0tIDhvaFpZYkozQ2VYVWdSdFhKMjhC
        eURLMGNqYTM1T3RWQlhuWkdwUVZnd0kKnIYEQjKLEtevE1RxY9DZXP/qyWcmpuFM
        I37i0K938Kvpi6ZfXxUrfFb3405GzcOiawIRO7VkNTVGKg+MOziI4g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age10e6ptnwuy76r2rx7cncp5gvh06eghvdungnhrkkea8t32caxjdxshwcy83
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MEpFaGE2VDVBeFRzT0xO
        cE5CRTg4SENWRlNEcjdGZ2d3VjNqcVlpVEhVCnArYVZmNnkyYzNHbSt2aTA1ZXNH
        REVGbHVlSmpsblBFU1F4RjNjSVpxOUUKLS0tICtCaXNrZVBYRS9aTk9laWlKN1Fw
        STBFTDhyWCt6Y0Z1Nm1vZ1FmN01VQm8KpZ7rJXPX+kn25YdTr/NqyyyxiqDQBDDV
        ex4VALkWP8m0f+Yla/Iilxshbws8DAY0NkhpVb16zCyKcsFqbctnLQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1gpm5lk2hvq49nxzr995ds9ps6u0vvkm2ve5rjxt4zv6sqj28symsq6cwmm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheHFLL2swR1F5RW1KZ2ZS
        MkdZTUVOZGlnZnJqWXVyQnQwUGlCQkIxUlVRCi9qb25YcEU1eHJYUFVpTFBIZ0t3
        VndVR0ZZVjF2b0wzMWFjYUJpdU93RkUKLS0tIEFMSnVBR0JpT05TWGg2dUxwcUY3
        YlRKdFE5dGpxQ1dSVHRhc0ZqZUZ6UFUKIkDdGHfEWUgOPCMz2bkXb4D+RrgVOKzU
        TcTYuWZ9i4rTVOHHW14GEuF+FiWJ2cHkGC9tV06JPPHLiA7S3uz+Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-05T16:37:23Z"
  mac: ENC[AES256_GCM,data:QxoGDCe4uV//3SR18BEv4YRvtCTcBwnPwxiLVkbNXOv+Jl7d08s7fssnf509ldlFbK2QzS6wyxIwTdGdDqPoaOTZx+P9sbnVher5aBhOhfAfwmqRkf9Ct0nd1K+ANDapdLLldqPEnGk10oztktLPGIe/ox/VpYmTDqHP1VVzYIw=,iv:wzuR6SGIDBkPUxBR1zMw1eUbsJJA9BmV6hYM4kkgsh4=,tag:ydiN3Cvuez/yd5lcMWnyQQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
