auth-key: ENC[AES256_GCM,data:GKQR/pVv4BNVyE/hGg0IKq+4xk0E5k3y0OdeMA6WKyd2dIEvVVKyNkmG6ZzqDeDlUm0mjQGzu4V35Jpy3Q==,iv:oFm074wo4PrXnV3244iuYTV4xYSseDwLN9jvs3WoFdc=,tag:ATLyiEHwF2msxC6z9XNsPg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10rvdume3yfwjxu2wc64dmkmc06qsm7fe0fvrpqt8mdrdksqx75vspwns56
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDFCUTU0aWx5dTJDWWNZ
        SVRPM0RoUXpyYU00MUJSQ0ZweWdqbkZlZVFvCnJEeENIZG1tQ1BXdWs5QUlXY3hE
        cm1SelhycG85WTN4anNEZTVuMlRsT3MKLS0tIE1kcDJ3b3VLMm9rWGlrVnVVTTZj
        RjViNlo5cHh2VmN6dVdGMHZIMm50T28KogO4+KjO7CYVBgsXGHx7GQ8Y9lua1brB
        bMTc82EtLKVb3zVK4F+rkd247B5K39YeQ+oAWd6Lbsg6mAfwAC4nlw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age10e6ptnwuy76r2rx7cncp5gvh06eghvdungnhrkkea8t32caxjdxshwcy83
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdVU2eThKZWVGTkVZNXBG
        OWhXR0pJSUtLRlFHdXAwWGJNSmZOOGFSSURRCmFpSkJnSzJFT2xidHpTWENmSndV
        MVRCMjNaVXMrWk9TVUZuOElvN0lQMEEKLS0tIDNLTGcwMWhnWDcwTVM1Ujg3VmRB
        dER1c0lDK2xOVUJBT1ZYeUtVZCs1bjgKcP5aWwniaS2xAmUuDPaI7gMBc5oaCYDq
        OMO3vq4BEBXzGNj+NXI/iTuCLvypJUqGmOdyzK72pIRzTJivnj1HyA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1gpm5lk2hvq49nxzr995ds9ps6u0vvkm2ve5rjxt4zv6sqj28symsq6cwmm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RGFvdk5sUlFPTy81Z2Nv
        S2ExSkhCQlZVcytreGZKMEMyOFpEcytaTDIwCnpnNkp1VmJkM05TTGFPbU9vZFJt
        djRBN2N3dlNlMWZCTXVIb3VsMGJlV2cKLS0tIEhPQUYyZTZ2bzBVWTB3ZWxzRk9M
        QnZyaWp2SDlJeHhHeFMzV29Ca01FYVUKuxN1en6QQ5BwsHhGJNeuini1cbdn4aNo
        dnaDDe1u/JgnFVH7urRnirRrM0+yJAN1ENq1CJ/z4w+Edd+mbf8sAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-05T16:34:57Z"
  mac: ENC[AES256_GCM,data:vvoBcdvhNfIYQZ2bjyVeB3X/W/pdjcUZx5exlTKq0n0FoCIFF9AFD4XmY/UcSXWzQoLJIkvrVP/+kSgVDHEwQW17jpykU6MsWGuH0aqPBXC6xDoGFK8D3Bh33SXsBsb7i6+P2apzDS/BmsOlN+DPhRCGb/PseAj99901U8HPSh0=,iv:58nw/xfvhE5mCuKUVpYCjqqrT9bp+7DWk9FD9FfKOsI=,tag:BE+Qr56pYhPnhnX69rNVBQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
